// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlEIjEBRBpkx6Llvdfa_XIVmoJ5v8Wno',
    appId: '1:855597525535:web:266289563e38b10c98032a',
    messagingSenderId: '855597525535',
    projectId: 'ica14-691a0',
    authDomain: 'ica14-691a0.firebaseapp.com',
    storageBucket: 'ica14-691a0.firebasestorage.app',
    measurementId: 'G-VQLRC5T2D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1H5pOaKHH5js07IRNHbop2lVRFj8V19U',
    appId: '1:855597525535:android:050a52f89e0f425998032a',
    messagingSenderId: '855597525535',
    projectId: 'ica14-691a0',
    storageBucket: 'ica14-691a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ihL7WP7Ji1dCZoi6L4yRtbLgrRhi9Hw',
    appId: '1:855597525535:ios:1d5053394eab730698032a',
    messagingSenderId: '855597525535',
    projectId: 'ica14-691a0',
    storageBucket: 'ica14-691a0.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ihL7WP7Ji1dCZoi6L4yRtbLgrRhi9Hw',
    appId: '1:855597525535:ios:1d5053394eab730698032a',
    messagingSenderId: '855597525535',
    projectId: 'ica14-691a0',
    storageBucket: 'ica14-691a0.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqlEIjEBRBpkx6Llvdfa_XIVmoJ5v8Wno',
    appId: '1:855597525535:web:8b75e7fda8e43a6498032a',
    messagingSenderId: '855597525535',
    projectId: 'ica14-691a0',
    authDomain: 'ica14-691a0.firebaseapp.com',
    storageBucket: 'ica14-691a0.firebasestorage.app',
    measurementId: 'G-KYY86RYS3L',
  );
}
